[package]
name = "hf-scanner"
edition = "2024"
description = "Honing calculator for Lost Ark"
repository = "https://github.com/Kenivia/Honing-Forecast"
license = "AGPL-3.0-or-later"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
js-sys = "0.3"
console_error_panic_hook = "0.1"
serde_json = "1.0"
either ={version = "1.16", features=["serde"]}
ahash = {version = "0.8", features=["serde"]}
fast_image_resize = "6.0.0"
image = {version = "0.25.10", default-features = false }
image-compare = "0.5.0"
imageproc = {version = "0.27.0", default-features = false }
uuid = {version="1.24.0", features=["serde", "v4"] }
